apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccount: jenkins-admin
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 600Mi
# 等容器全部启动正常才开启健康检查,避免由于配置低气动慢造成的循环重启
# #        livenessProbe:
# #          httpGet:
# #            path: /login
# #            port: 8080
# #          initialDelaySeconds: 60
# #          timeoutSeconds: 5
# #          failureThreshold: 12
# #        readinessProbe:
# #          httpGet:
# #            path: /login
# #            port: 8080
# #          initialDelaySeconds: 60
# #          timeoutSeconds: 5
# #          failureThreshold: 12
# #
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: pvc-jenkins

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: jenkins
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
